version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      all:
        pattern: '*'

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    groups:
      all:
        pattern: '*'
