language: node_js
script:
- npm run lint
- npm run dist
- npm test
env:
  # NGROK_AUTH_TOKEN
  secure: KatepAacTQlhrJMYrYuQXwXh1SZUWTbYaJFyhwduuJn0z09Z7a6z2p+5qUkQBLQfubj+OmMyofZvQqlskpuxDG2l+FjU9m7p/cG11o6oHrZp+og4SDQI0JyCCazJl69Mun4Q8oOOwcOCRS7KAeyzH50t+cAZ5xhyXMwocKog62E=
deploy:
  provider: npm
  email: marius@accoplex.com
  api_key:
    secure: jyOlnZKkGmt1/3YH3Gs00zkOD7R0iXmHhtSsWCXrtlWXr8XqjH5DH6WRNOvr2JnI1NJO2Zz0e1EAjKNbUVfS/SWELlR9GX+yJr9QtgWce92zizL4Finp3VeGtZ8ZBBukbPogQW80Dvc8zb2FhpnxdW83lGlqGqyL7o7BT+0S7tQ=
  skip_cleanup: true
  on:
    tags: true
    repo: tus/tus-js-client
