name: CI
on:
  push:
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  content:
    if: "!contains(github.event.pull_request.title, 'WIP: ')"
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - desc: "Browserstack"
            suite: "test-browserstack"
            node: 16
          - desc: "Puppeteer"
            suite: "test-puppeteer"
            node: 16
          - desc: "Lint & Types"
            suite: "lint test-types"
            node: 16
          - desc: "Node 14"
            suite: "test-node"
            node: 14
          - desc: "Node 16"
            suite: "test-node"
            node: 16
          - desc: "Node 18"
            suite: "test-node"
            node: 18
    name: ${{ matrix.desc }}
    steps  : 
      - name: Check out sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Git Clean
        run: git clean -fxd --exclude=node_modules/
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        uses: sergioramos/yarn-actions/install@v6
        with:
          frozen-lockfile: true
      - name: Build
        uses: sergioramos/yarn-actions/run@v6
        with:
          script: build
      - name: Test
        uses: sergioramos/yarn-actions/run@v6
        with:
          script: ${{ matrix.suite }}

# @TODO: port this Travis CI automation to GHA one day:
# deploy:
#   provider: npm
#   email: marius@transloadit.com
#   api_token:
#     secure: deLv8rCb1nN4vcFCSlPLVLcZJ20vLWNPaAA4PZAUXcQdUFX8mc++qDusS0o3LqdQVIugeOkSBTuKq8GQxOpMahj3U0WDe7Dy+t5xS/kPejr1H4m/VT1A5uRfBLGHgjuQzZH1L/RzAAca7Przx9fNe/1y1+RblDbbE7oOXQWiIUs=
#   skip_cleanup: true
#   on:
#     tags: true
#     repo: tus/tus-js-client
#     node_js: 12